ROBLOX = "roblox"
AEGIS = "aegis"
OPENAI_MOD = "openai_mod"
BEAVERTAILS = "beavertails"
TOXICCHAT = "toxic_chat"
WILDGUARD_PROMPT = "wildguard_prompt"
WILDGUARD_RESPONSE = "wildguard_response"
HARMBENCH = "harmbench"
